### ISSUE TITLE
Shell Window Add-On

### ISSUE THREAD

**Issue by nietoperz809** [EgonOlsen71/basicv2#2]
Look here: https://github.com/nietoperz809/OlsenBasic/tree/master/src/main/java/com/sixtyfour/basicshell
Add this package to your code and run the ShellFrame Class.

It works almost like an original C64-Editor :)

**Comment by EgonOlsen71** [comment]
Nice work! I noticed a small issue with stopping the program. Something like

10 goto 10

can be stopped just fine now. But if I add some output, like

10 print"hello":goto10

then the stop event never comes, i.e. the button click won't be recognized.

**Comment by EgonOlsen71** [comment]
Another issue: 

`10 input a`

works fine, but something like

`10 input"test";a`

doesn't, because the actual input will be "est?<number>" in that case.

**Comment by nietoperz809** [comment]
in ShellInputProvider readString() 
`        String s = shellFrame.getString();
        s = s.substring(s.lastIndexOf('?')+1);
`
should fix this.

**Comment by EgonOlsen71** [comment]
Yes, it does. I used indexOf() instead, because lastIndexOf() would prevent you from using a question mark in your actual input string, but anyway...

**Comment by EgonOlsen71** [comment]
I've added the current state to the repository now.

**Comment by EgonOlsen71** [comment]
I've modified your code slightly to look more C64 like and I sadly had to remove the Java8 related stuff, because I have to stay compatible with 6/7 because of...reasons.
I also renamed the actual shell class to make it more clear what it actually is (IMHO).

The issue mentioned above (not being able to stop programs with heavy output) still exists, but it seems like a GUI/event thread issue to me at first glance. I won't bother with it for now.

Again, this is very nice work. Thanks for coding this and for making it available! I really appreciate it.

**Comment by nietoperz809** [comment]
Thanks, Egon. I also like your CBM-Basic very much. Great work!
Btw, regarding the Input problem with the question mark: I hope that I now have the final fix. Please see my repo.

**Comment by EgonOlsen71** [comment]
I see. I ported that change as well as some others like the dir command and the tooltip. I also tried to port the BlockCaret, but it totally screwed up rendering then a little more was visible on screen and I moved the cursor.

**Comment by nietoperz809** [comment]
OK, it now has the blinking bock caret from a groovy text editor.
look in my repo ...

**Comment by nietoperz809** [comment]
Apropos caret: the new code has a caret listener to get the line number. This is much faster than the old iterative getLinePos() function that counts the rows. :)

**Comment by EgonOlsen71** [comment]
Ported both changes into my repo, works much better now...:-)

**Comment by nietoperz809** [comment]
Hi Egon,
take a look at my new version. For a quick overview run the executable in out/artifacts/OlsenBasic_jar
It has a nice C64 font, copy/paste-support, and so on. 
Font source is: http://www.commodoreserver.com/BlogEntryView.asp?EID=C1BE965E77A14734875AD8018497C154

**Comment by EgonOlsen71** [comment]
Nice! I've ported most of your changes to my repo as well. My immediate mode implementation is still different and so are the colors and such, but anyway...
I've also added some simple truncation to the text area, so that 10print"hello":goto10 doesn't bring the system to a halt.

**Comment by nietoperz809** [comment]
Hi,
I made another C64 shell that is able to display colors.
It has a C64 character ROM and simulates color RAM like a real sixtyfour
it is also much faster (doesn't need a Swing TextArea anymore)
--> https://github.com/nietoperz809/C64Screen

Try out the jar or build it yourself.   :)

10 FOR S = 0 TO 15
20 POKE 646,S
21 FOR N=0 TO 39
40 PRINT CHR$ (128);
41 NEXT N
50 PRINT 
70 NEXT S

**Comment by nietoperz809** [comment]
Btw, run-stop is CTRL-C

**Comment by EgonOlsen71** [comment]
Looks very nice and feel quite authentic. I'll stick with my fork of your first implementation for now, though. Using a TextArea has it's drawbacks, but it has its advantages as well.
